apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo.yaml
  - server.yaml
  - client.yaml
  - rbac.yaml
  - network-policy.yaml
  - secret-provider.yaml

images:
  - name: devopscommerce.azurecr.io/server
    newTag: latest
  - name: devopscommerce.azurecr.io/client
    newTag: latest
