apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: server-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: 'false'
    useVMManagedIdentity: 'true'
    userAssignedIdentityID: ''
    keyvaultName: kv-ecommerce-devops
    tenantId: ''
    objects: |
      array:
        - |
          objectName: JWT-SECRET
          objectType: secret
  secretObjects:
    - secretName: server-secrets
      type: Opaque
      data:
        - objectName: JWT-SECRET
          key: JWT_SECRET
